- &hook
  id: nbdev_clean
  name: nbdev_clean
  entry: nbdev_clean
  description: "Clean metadata from notebooks to avoid merge conflicts"
  language: python
  always_run: true
  pass_filenames: false

- <<: *hook
  id: nbdev_export
  name: nbdev_export
  entry: nbdev_export
  description: "Export notebooks to modules and build modidx"

- <<: *hook
  id: nbdev_docs
  name: nbdev_docs
  entry: nbdev_docs
  description: "Create Quarto docs and README.md"
