"""Configuring nbdev and bootstrapping notebook export

Docs: https://nbdev.fast.ai/api/config.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/01_config.ipynb.

# %% auto #0
__all__ = ['pyproject_nm', 'pyproject_tmpl', 'nbdev_defaults', 'pyproj_tmpl', 'nbdev_create_config', 'ConfigToml', 'get_config',
           'is_nbdev', 'create_output', 'show_src', 'nbpath2html', 'nbpath2docurl', 'read_version', 'set_version',
           'bump_version', 'update_version', 'update_proj', 'add_init', 'pkg_mdoc', 'update_init_mdoc', 'pkg_llms',
           'update_llms_txt', 'import_obj', 'write_cells']

# %% ../nbs/api/01_config.ipynb #6fd14ecd
from fastcore.docments import *
from fastcore.utils import *
from fastcore.meta import *
from fastcore.script import *
from fastcore.style import *
from fastcore.xdg import *

import ast,importlib,re
from IPython.display import Markdown
from fastcore.nbio import read_nb,NbCell

try: import tomllib
except ImportError: import tomli as tomllib

# %% ../nbs/api/01_config.ipynb #117128e6
pyproject_nm = 'pyproject.toml'
_nbdev_home_dir = 'nbdev'
_user_cfg_name = 'config.toml'

# %% ../nbs/api/01_config.ipynb #adf0834f
def _git_repo():
    try: return repo_details(run('git config --get remote.origin.url'))[1]
    except OSError: return

# %% ../nbs/api/01_config.ipynb #6eeafafd
def _get_info(owner, repo, default_branch='main', default_kw='nbdev'):
    from ghapi.all import call_gh, APIError
    try: r = call_gh('repos.get', owner=owner, repo=repo)
    except APIError:
        # chkstyle: ignore-node
        msg= [f"""Could not access repo: {owner}/{repo} to find your default branch - `{default_branch}` assumed.
Edit `pyproject.toml` if this is incorrect.
In the future, you can allow nbdev to see private repos by setting the environment variable GITHUB_TOKEN as described here:
https://nbdev.fast.ai/api/release.html#setup"""]
        print(''.join(msg))
        return default_branch,default_kw,''

    return r.default_branch, default_kw if not getattr(r, 'topics', []) else ' '.join(r.topics), r.description

# %% ../nbs/api/01_config.ipynb #35d5c037
def _fetch_from_git(raise_err=False):
    "Get information for pyproject.toml from git."
    res={}
    try:
        res['author'] = run('git config --get user.name').strip()
        res['author_email'] = run('git config --get user.email').strip()
    except OSError as e:
        if raise_err: raise e
    try:
        url = run('git config --get remote.origin.url')
        res['user'],res['repo'] = repo_details(url)
        res['branch'],res['keywords'],desc = _get_info(owner=res['user'], repo=res['repo'])
        if desc: res['description'] = desc
        res['lib_name'] = res['repo'].replace('-','_')
    except OSError as e:
        if raise_err: raise e
    return res

# %% ../nbs/api/01_config.ipynb #05aae09f
pyproject_tmpl = '''[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "{name}"
dynamic = ["version"]
description = "{description}"
readme = "README.md"
requires-python = ">={min_python}"
license = {{text = "{license}"}}
authors = [{{name = "{author}", email = "{author_email}"}}]
keywords = {keywords}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = []

[project.urls]
Repository = "{git_url}"
Documentation = "{doc_url}"

[project.entry-points.nbdev]
{lib_path} = "{lib_path}._modidx:d"

[tool.setuptools.dynamic]
version = {{attr = "{lib_path}.__version__"}}

[tool.setuptools.packages.find]
include = ["{lib_path}"]

[tool.nbdev]
'''

# %% ../nbs/api/01_config.ipynb #3fc5c33f
@call_parse
def nbdev_create_config(
    repo:str=None, # Repo name
    branch:str='main', # Repo default branch
    user:str=None, # Repo username
    author:str=None, # Package author's name
    author_email:str=None, # Package author's email address
    description:str='', # Short summary of the package
    path:str='.', # Path to create config file
    min_python:str='3.10', # Minimum Python version
    license:str='Apache-2.0', # License (SPDX identifier)
):
    "Create a pyproject.toml config file."
    path = Path(path)
    path.mkdir(exist_ok=True, parents=True)
    
    # Infer from git if not provided
    inf = _fetch_from_git()
    repo = repo or inf.get('repo') or path.resolve().name
    user = user or inf.get('user', '')
    if not user: raise ValueError("Could not infer `user` from git. Please pass --user explicitly.")
    author = author or inf.get('author', '')
    if not author: raise ValueError("Could not infer `author` from git. Please pass --author explicitly.")
    author_email = author_email or inf.get('author_email', '')
    if not author_email: raise ValueError("Could not infer `author_email` from git. Please pass --author_email explicitly.")
    branch = branch or inf.get('branch', 'main')
    description = description or inf.get('description', '')
    
    lib_path = repo.replace('-', '_')
    git_url = f"https://github.com/{user}/{repo}" if user else ''
    doc_url = f"https://{user}.github.io/{repo}/" if user else ''
    keywords = inf.get('keywords', 'nbdev').split()
    
    txt = pyproject_tmpl.format(name=repo, lib_path=lib_path, description=description, min_python=min_python, license=license,
        author=author, author_email=author_email, keywords=keywords, git_url=git_url, doc_url=doc_url, branch=branch)
    
    cfg_file = path / pyproject_nm
    if cfg_file.exists(): warn(f'{cfg_file} already exists')
    else:
        cfg_file.write_text(txt)
        print(f'{cfg_file} created.')

# %% ../nbs/api/01_config.ipynb #0e56064f
def _load_toml(p):
    "Load TOML file at `p` into a dict"
    return tomllib.loads(Path(p).read_text(encoding='utf-8'))

def _has_nbdev(p):
    "True if pyproject.toml at `p` has [tool.nbdev]"
    try: return _load_toml(p).get('tool', {}).get('nbdev') is not None
    except Exception: return False

def _find_nbdev_pyproject(path=None):
    "Find nearest pyproject.toml containing [tool.nbdev], walking up from `path`"
    p = Path(path or Path.cwd()).resolve()
    for d in [p] + list(p.parents):
        f = d/pyproject_nm
        if f.exists() and _has_nbdev(f): return f
    for d in [p] + list(p.parents):
        if (d/'settings.ini').exists():
            raise ValueError(f"Found old settings.ini. Migrate to pyproject.toml using `nbdev-migrate-config`. See https://nbdev.fast.ai/getting_started.html")

# %% ../nbs/api/01_config.ipynb #3dac70e0
nbdev_defaults = dict(nbs_path='nbs', doc_path='_docs', tst_flags='notest', recursive=True, readme_nb='index.ipynb',
    clean_ids=True, clear_all=False, put_version_in_init=True, jupyter_hooks=False, custom_sidebar=False, branch='main',
    doc_procs=[], export_procs=[], exec_profile=True)

_path_keys = 'lib_path', 'nbs_path', 'doc_path'

# %% ../nbs/api/01_config.ipynb #165ff301
class ConfigToml(AttrDict):
    def __init__(self, d, proj, cfg_file):
        super().__init__({**nbdev_defaults, **d})
        self.config_file = cfg_file
        self.config_path = cfg_file.parent
        
        self.lib_name = proj.get('name', '')
        self.title = self.get('title') or self.lib_name
        self.description = proj.get('description', '')
        self.keywords = proj.get('keywords', [])
        self.min_python = (proj.get('requires-python') or '>=3.9').lstrip('>=')
        auths = proj.get('authors') or [{}]
        self.author = auths[0].get('name')
        self.author_email = auths[0].get('email')
        
        
        urls = proj.get('urls') or {}
        self.git_url = (urls.get('Repository') or urls.get('Source') or '').rstrip('/')
        self.doc_url = urls.get('Documentation') or ''
        self.user, self.repo = repo_details(self.git_url) if self.git_url else ('', '')
        # Derive doc_host and doc_baseurl from doc_url
        from urllib.parse import urlparse
        u = urlparse(self.doc_url)
        self.doc_host = f"{u.scheme}://{u.netloc}" if u.scheme else ''
        self.doc_baseurl = (u.path or '/').rstrip('/') or '/'
        if 'lib_path' not in self: self['lib_path'] = self.lib_name.replace('-', '_')

    @property
    def version(self): return read_version(self.config_path / self['lib_path']) or '0.0.1'

    @property
    def d(self): return {k:v for k,v in super().items()}

    def __getattr__(self, k): return stop(AttributeError(k)) if k=='d' or k not in self.d else self.get(k)
    def __getitem__(self, k): return stop(IndexError(k)) if k not in self.d else self.get(k)

    def get(self, k, default=None):
        v = self.d.get(k, default)
        if v is None: return None
        return self.config_path / v if k in _path_keys else v

    def path(self, k, default=None):
        v = self.d.get(k, default)
        return v if v is None else self.config_path / v

# %% ../nbs/api/01_config.ipynb #6fed9c91
def _user_config():
    "Load user config from ~/.config/nbdev/config.toml if it exists"
    p = xdg_config_home() / _nbdev_home_dir / _user_cfg_name
    if p.exists(): return _load_toml(p)
    return {}

# %% ../nbs/api/01_config.ipynb #f6660849
def get_config(path=None, also_settings=False):
    "Return nbdev config."
    cfg_file = _find_nbdev_pyproject(path)
    if cfg_file is not None:
        d = _load_toml(cfg_file)
        user = _user_config()
        nbdev = {**user, **d.get('tool', {}).get('nbdev', {})}
        return ConfigToml(nbdev, d.get('project', {}), cfg_file)
    if also_settings:
        from fastcore.xtras import Config
        cfg = Config.find('settings.ini', path)
        if cfg: return cfg
    cfg_path = Path(path or Path.cwd()).expanduser().absolute()
    return ConfigToml(nbdev_defaults, {}, cfg_path/'pyproject.toml')

# %% ../nbs/api/01_config.ipynb #6939b40e
def is_nbdev(path=None): return _find_nbdev_pyproject(path) is not None

# %% ../nbs/api/01_config.ipynb #6e89fe6c
def create_output(txt, mime):
    "Add a cell output containing `txt` of the `mime` text MIME sub-type"
    return [dict(data={f"text/{mime}": str(txt).splitlines(True)},
        execution_count=1, metadata={}, output_type="execute_result")]

# %% ../nbs/api/01_config.ipynb #5a4d8e52
def show_src(src, lang='python'): return Markdown(f'```{lang}\n{src}\n```')

# %% ../nbs/api/01_config.ipynb #14a9c607
def nbpath2html(p):
    "Convert notebook path `p` to its html doc path (strips numeric prefix)"
    p = Path(p)
    return p.with_name(re.sub(r'^\d+[a-zA-Z0-9]*_', '', p.name.lower())).with_suffix('.html')

# %% ../nbs/api/01_config.ipynb #c830bb2b
def nbpath2docurl(nb_path):
    "Hosted docs URL (with `.md` suffix) for notebook `nb_path`, or '' if no `doc_host`"
    cfg = get_config()
    if not cfg.doc_host: return ''
    try: p = Path(nb_path).resolve().relative_to(cfg.path('nbs_path'))
    except ValueError: return ""
    return f"{cfg.doc_host.rstrip('/')}{cfg.doc_baseurl.rstrip('/')}/{nbpath2html(p).as_posix()}.md"

# %% ../nbs/api/01_config.ipynb #163177f2
pyproj_tmpl = """[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "FILL_IN"
requires-python="FILL_IN"
dynamic = [ "keywords", "description", "version", "dependencies", "optional-dependencies", "readme",
    "license", "authors", "classifiers", "entry-points", "scripts", "urls"]

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "setup.py" }]
"""

# %% ../nbs/api/01_config.ipynb #f1c85f45
_re_version = re.compile(r'^__version__\s*=\s*[\'"]([^\'"]+)[\'"]', re.MULTILINE)
_re_proj = re.compile(r'(\[project\](?:\n(?!\[).*)*?\n)name\s*=\s*"[^"]*"')
_re_reqpy = re.compile(r'^requires-python\s*=\s*".*$', re.MULTILINE)
_init = '__init__.py'
_pyproj = 'pyproject.toml'

# %% ../nbs/api/01_config.ipynb #680e62a5
def read_version(path):
    "Read __version__ from `path/__init__.py`, or None if not found"
    fname = Path(path)/_init
    if not fname.exists(): return None
    m = _re_version.search(fname.read_text())
    return m.group(1) if m else None

# %% ../nbs/api/01_config.ipynb #cf0fc6a3
def set_version(path, version):
    "Set __version__ in `path/__init__.py`"
    path = Path(path)
    path.mkdir(exist_ok=True, parents=True)
    fname = path/_init
    if not fname.exists(): fname.touch()
    ver_line = f'__version__ = "{version}"'
    code = fname.read_text()
    if _re_version.search(code) is None: code = ver_line + "\n" + code
    else: code = _re_version.sub(ver_line, code)
    fname.write_text(code)

# %% ../nbs/api/01_config.ipynb #d00889e5
def bump_version(v, part=2, unbump=False):
    "Bump semver part `part` (0=major, 1=minor, 2=patch), counted from the right"
    parts = (v or '0.0.0').split('.')
    parts += ['0'] * (3 - len(parts))
    idx = len(parts) - 3 + part
    parts[idx] = str(int(parts[idx]) + (-1 if unbump else 1))
    for i in range(idx+1, len(parts)): parts[i] = '0'
    return '.'.join(parts)

# %% ../nbs/api/01_config.ipynb #e32583e6
def update_version(path=None):
    "Add __version__ to `path/__init__.py` if it doesn't exist"
    path = Path(path or get_config().lib_path)
    if read_version(path) is None: set_version(path, get_config().version)

# %% ../nbs/api/01_config.ipynb #275ef862
def _has_py(fs): return any(1 for f in fs if f.endswith('.py'))

def update_proj(path):
    "Create or update `pyproject.toml` in the project root."
    fname = path/_pyproj
    if not fname.exists(): fname.write_text(pyproj_tmpl)
    txt = fname.read_text()
    txt = _re_proj.sub(rf'\1name = "{get_config().lib_name}"', txt)
    txt = _re_reqpy.sub(f'requires-python = ">={get_config().min_python}"', txt)
    fname.write_text(txt)

# %% ../nbs/api/01_config.ipynb #bdf57184
def add_init(path=None):
    "Add `__init__.py` in all subdirs of `path` containing python files if it's not there already."
    # we add the lowest-level `__init__.py` files first, which ensures _has_py succeeds for parent modules
    path = Path(path or get_config().lib_path)
    path.mkdir(exist_ok=True)
    if not (path/_init).exists(): (path/_init).touch()
    for r,ds,fs in os.walk(path, topdown=False):
        r = Path(r)
        subds = (os.listdir(r/d) for d in ds)
        if _has_py(fs) or any(filter(_has_py, subds)) and not (r/_init).exists(): (r/_init).touch()
    if get_config().get('put_version_in_init', True): update_version(path)
    if get_config().get('update_pyproject', True): update_proj(path.parent)
    update_init_mdoc(path)

# %% ../nbs/api/01_config.ipynb #a01b98bb
def _mod_docstr(py_path):
    "Module docstring of `py_path` via ast, without importing ('' if none or unparseable)"
    try: return ast.get_docstring(ast.parse(Path(py_path).read_text(encoding='utf-8'))) or ''
    except SyntaxError: return ''

def _substantive(docstr):
    "Does `docstr` say more than the default summary line plus `Docs:` link?"
    return len(docstr.strip().splitlines())>3

def _pkg_mods(path):
    "`(name, summary, url)` per module of `path` with a substantive docstring: dotted name, one-line first para, `Docs:` url"
    res = []
    for p in sorted(Path(path).rglob('*.py')):
        if p.name.startswith('_'): continue
        d = _mod_docstr(p)
        if not _substantive(d): continue
        nm = '.'.join((Path(path).name, *p.relative_to(path).with_suffix('').parts))
        summ = ' '.join(d.split('\n\n')[0].splitlines())
        last = d.strip().splitlines()[-1]
        res.append((nm, summ, last[5:].strip() if last.startswith('Docs:') else ''))
    return res

def _index_mdoc(idx_path):
    "Package docstring intro: bodies of md cells with an export directive, and fenced `exportd` cells, from the index nb"
    if not idx_path or not Path(idx_path).exists(): return ''
    docs = []
    for c in read_nb(idx_path).cells:
        lines = c.source.splitlines()
        n = 0
        while n<len(lines) and lines[n].startswith('#|'): n += 1
        dirs = {l[2:].strip().split()[0] for l in lines[:n] if l[2:].strip()}
        body = '\n'.join(lines[n:]).strip()
        if not body or not {'export','exportd'}&dirs: continue
        docs.append(body if c.cell_type=='markdown' else fenced(body, 'python'))
    return '\n\n'.join(docs)

def _pkg_docparts(path=None, desc=None, index_nb=None):
    "`(path, desc, intro, mods)` shared by `pkg_mdoc` and `pkg_llms`"
    path = Path(path or get_config().lib_path)
    mods = _pkg_mods(path)
    if index_nb is None:
        cfg = get_config()
        if path==Path(cfg.lib_path): index_nb = cfg.nbs_path/cfg.readme_nb
    intro = _index_mdoc(index_nb)
    if (mods or intro) and desc is None: desc = get_config().description
    return path,desc,intro,mods

def pkg_mdoc(path=None, desc=None, index_nb=None):
    "Package docstring for `path`: `desc`, intro from `index_nb`, and a line per module with a substantive docstring"
    path,desc,intro,mods = _pkg_docparts(path, desc, index_nb)
    if not mods and not intro: return ''
    mods = ['Modules:', '\n'.join(f'- `{nm}`: {summ}' for nm,summ,url in mods)] if mods else []
    return '\n\n'.join(filter(None, [desc, intro, *mods]))

# %% ../nbs/api/01_config.ipynb #a03a0007
def update_init_mdoc(path=None, desc=None):
    "Write `pkg_mdoc` as the docstring of `path/__init__.py`, replacing any existing docstring"
    path = Path(path or get_config().lib_path)
    mdoc = pkg_mdoc(path, desc=desc)
    fn = path/'__init__.py'
    txt = fn.read_text(encoding='utf-8') if fn.exists() else ''
    body = ast.parse(txt).body
    rest,cur = txt,''
    if body and isinstance(body[0], ast.Expr) and isinstance(getattr(body[0].value, 'value', None), str):
        cur = body[0].value.value
        rest = ''.join(txt.splitlines(keepends=True)[body[0].end_lineno:])
    if not mdoc:
        if '\nModules:\n' not in cur: return
        mdoc = desc if desc is not None else get_config().description
    res = f'"""{mdoc}"""\n'
    if rest.strip(): res += '\n'+rest.lstrip('\n')
    fn.write_text(res, encoding='utf-8')

# %% ../nbs/api/01_config.ipynb #f9912ef7
_llms_marker = '<!-- Generated by nbdev-export; edit the index notebook, not this file -->'

def _modline(nm, summ, url):
    "llms.txt list line: linked when `url` is a single URL, else the `Docs:` text carried verbatim"
    if url and ' ' not in url: return f'- [{nm}]({url}): {summ}'
    return f'- `{nm}`: {summ} (Docs: {url})' if url else f'- `{nm}`: {summ}'

def pkg_llms(path=None, desc=None, index_nb=None):
    "llms.txt for the package at `path`, from the same sources as `pkg_mdoc` ('' if no intro or modules)"
    path,desc,intro,mods = _pkg_docparts(path, desc, index_nb)
    if not mods and not intro: return ''
    if mods:
        links = '\n'.join(_modline(*o) for o in mods)
        mods = [f'## Modules\n\n{links}']
    parts = [f'# {path.name}', f'> {desc}' if desc else '', intro, *mods, _llms_marker]
    return '\n\n'.join(filter(None, parts)) + '\n'

def update_llms_txt(path=None, fn=None, desc=None, index_nb=None):
    "Write `pkg_llms` to `fn` when it's absent or generated (has the nbdev marker)"
    if fn is None: fn = get_config().nbs_path/'llms.txt'
    txt = pkg_llms(path, desc=desc, index_nb=index_nb)
    if fn.exists() and _llms_marker not in fn.read_text(encoding='utf-8'): return
    if not txt:
        if fn.exists(): fn.unlink()
        return
    fn.write_text(txt, encoding='utf-8')

# %% ../nbs/api/01_config.ipynb #95cebda6
def import_obj(s):
    "Import and return `module:obj` string"
    mod_nm, obj_nm = s.split(':')
    mod = importlib.import_module(mod_nm)
    return getattr(mod, obj_nm)

# %% ../nbs/api/01_config.ipynb #cdd05b4c
def write_cells(cells, hdr, file, solo_nb=False):
    "Write `cells` to `file` along with header `hdr` (mainly for nbdev internal use)."
    for cell in cells:
        if cell.cell_type=='code' and cell.source.strip() and 'exportd' not in getattr(cell,'directives_',{}):
            cell_id = f" #{cell.id}" if cell.get('id') else ""
            file.write(f'\n\n{hdr}{cell_id}\n{cell.source}') if not solo_nb else file.write(f'\n\n{cell.source}')

# %% ../nbs/api/01_config.ipynb #34cfeb82
def _basic_export_nb(fname, name, dest=None):
    "Basic exporter to bootstrap nbdev."
    if dest is None: dest = get_config().lib_path
    add_init()
    fname,dest = Path(fname),Path(dest)
    nb = read_nb(fname)

    # grab the source from all the cells that have an `export` comment
    cells = L(cell for cell in nb.cells if re.match(r'#\s*\|export', cell.source))

    # find all the exported functions, to create `__all__`:
    trees = cells.map(NbCell.parsed_).concat()
    funcs = trees.filter(risinstance((ast.FunctionDef,ast.ClassDef))).attrgot('name')
    exp_funcs = [f for f in funcs if f[0]!='_']

    # write out the file
    with (dest/name).open('w',encoding="utf-8") as f:
        f.write(f"# %% auto 0\n__all__ = {exp_funcs}")
        write_cells(cells, f"# %% {fname.relpath(dest)}", f)
        f.write('\n')
