"""Get ipynb diffs by cell"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/19_diff.ipynb.

# %% auto 0
__all__ = ['source_diff']

# %% ../nbs/api/19_diff.ipynb
def source_diff(
    old_source, # Original source string
    new_source # New source string
): # Unified diff string
    "Return unified diff string for source change"
    return '\n'.join(unified_diff(old_source.splitlines(), new_source.splitlines(), lineterm=''))
