"""A YAML and formatted-markdown frontmatter processor

Docs: https://nbdev.fast.ai/api/frontmatter.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/09_frontmatter.ipynb.

# %% auto #0
__all__ = ['FrontmatterProc']

# %% ../nbs/api/09_frontmatter.ipynb #2398f5ef-06d3-4890-8a54-7cf4f81f3894
from .imports import *
from .process import *
from .config import nbpath2html

from fastcore.nbio import *
from fastcore.imports import *
import yaml

# %% ../nbs/api/09_frontmatter.ipynb #6d13ecdb
_RE_FM_BASE=r'''^---\s*
(.*?\S+.*?)
---\s*'''

_re_fm_md = re.compile(_RE_FM_BASE, flags=re.DOTALL)


# %% ../nbs/api/09_frontmatter.ipynb #1725f3b9
def _fm2dict_md(s:str):
    "Load YAML frontmatter opening a markdown file (body allowed) into a `dict`"
    match = _re_fm_md.search(s.strip())
    return yaml.safe_load(match.group(1)) if match else {}


# %% ../nbs/api/09_frontmatter.ipynb #1b5d9d32
def _dict2fm(d): return f'---\n{yaml.dump(d)}\n---\n\n'
def _insertfm(nb, fm): nb.cells.insert(0, mk_cell(_dict2fm(fm), 'raw'))

class FrontmatterProc(Processor):
    "A YAML and formatted-markdown frontmatter processor"
    def begin(self): self.fm = getattr(self.nb, 'frontmatter_', {})

    def _update(self, f, cell):
        s = cell.get('source')
        if not s: return
        d = f(s)
        if not d: return
        self.fm.update(d)
        cell.source = None

    def cell(self, cell):
        if cell.cell_type=='raw': self._update(cell_frontmatter, cell)
        elif cell.cell_type=='markdown' and 'title' not in self.fm: self._update(md_frontmatter, cell)

    def end(self):
        self.nb.frontmatter_ = self.fm
        if not self.fm: return
        if not hasattr(self.nb, 'path_'):
            raise AttributeError('Notebook missing `path_` attribute.\n\nPlease remove any nbdev-related notebook filters '
                                 'from your _quarto.yml file (e.g. `ipynb-filter: [nbdev_filter]`), since they are no '
                                 'longer supported as of nbdev v2.3. See the v2.3 launch post for more information: '
                                 'https://forums.fast.ai/t/upcoming-changes-in-v2-3-edit-now-released/98905.')
        self.fm.update({'output-file': nbpath2html(Path(self.nb.path_)).name})
        _insertfm(self.nb, self.fm)
