"""Build nbdev documentation with Octavo

Docs: https://nbdev.fast.ai/api/octavo.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/21_octavo.ipynb.

# %% auto #0
__all__ = ['OctavoProc', 'local_libraries', 'render_script', 'script_pages', 'octavo_config', 'octavo_docs', 'octavo_readme']

# %% ../nbs/api/21_octavo.ipynb #fd0fd32f
from contextlib import redirect_stdout
from io import StringIO
from fastcore.utils import *
import yaml
from .config import get_config, import_obj, _load_toml
from .doclinks import NbdevLookup
from .process import NBProcessor
from .processors import FilterDefaults, add_links
from .serve import _is_qpy
from octavo.site import Site
from octavo.pages import Page, GeneratedFile, scan, page_nm, hidden, ipynb2md
from octavo.core import md2doc
from mdhtml import md2gfm
from .quarto import _doc_mtime_not_older

# %% ../nbs/api/21_octavo.ipynb #1cc66460
class OctavoProc(FilterDefaults):
    "Process nbdev notebooks for Octavo without changing Quarto defaults"
    def __init__(self, local_lib=None, strip_libs=None): self.nl = NbdevLookup(strip_libs=strip_libs or local_lib, local_lib=local_lib)
    def add_links(self, cell): return add_links(cell, nl=self.nl)
    def procs(self): return L(self.add_links if o is add_links else o for o in super().procs())
    def nb_proc(self, nb): return NBProcessor(nb=nb, procs=self.procs(), rm_directives=False)

    def __call__(self, nb):
        super().__call__(nb)
        if getattr(nb, 'frontmatter_', None) and nb.cells[0].cell_type=='raw': nb.cells[0].cell_type = 'markdown'

# %% ../nbs/api/21_octavo.ipynb #9a0258ee
def local_libraries(cfg):
    "Names of the project's declared nbdev symbol indexes"
    proj = _load_toml(cfg.config_file).get('project', {})
    return tuple(proj.get('entry-points', {}).get('nbdev', {}))

# %% ../nbs/api/21_octavo.ipynb #f9f85ebf
def render_script(path):
    "Captured stdout from a double-suffix render script; prepend optional `.md.py` frontmatter"
    path = Path(path)
    if path.suffix!='.py' or len(path.suffixes)<2: return
    fm = _is_qpy(path) if path.name.endswith('.md.py') else None
    f = StringIO()
    with redirect_stdout(f): exec(compile(path.read_text(encoding='utf-8'), str(path), 'exec'), {})
    return (f'---\n{fm}\n---\n\n' if fm else '') + f.getvalue()

# %% ../nbs/api/21_octavo.ipynb #e85c51f3
def script_pages(root):
    "Render scripts under `root`: `*.md.py` as `Page`s, anything else as `GeneratedFile`s"
    root,pages,files = Path(root),L(),L()
    for o in sorted(root.rglob('*.py')):
        rel = o.relative_to(root)
        if hidden(rel) or (txt:=render_script(o)) is None: continue
        dest = rel.with_suffix('')
        if dest.suffix=='.md': pages.append(Page(str(rel), txt, nm=page_nm(dest)))
        else: files.append(GeneratedFile(str(rel), str(dest), txt))
    return pages,files

# %% ../nbs/api/21_octavo.ipynb #d6904375
def octavo_config(root):
    "Read an existing octavo.yml mapping before running project code"
    root = Path(root)
    if not (root/'octavo.yml').is_file(): raise FileNotFoundError(root/'octavo.yml')
    settings = yaml.safe_load((root/'octavo.yml').read_text())
    if settings is None: return {}
    if not isinstance(settings, dict): raise ValueError(f'{root / "octavo.yml"} must contain a YAML mapping')
    return settings

# %% ../nbs/api/21_octavo.ipynb #f6830357
def octavo_docs(
    path:str=None, # Path to the project or its notebooks
):
    "Create Octavo docs and run the optional docs_post_build callback"
    cfg = get_config(path)
    settings = octavo_config(cfg.nbs_path)
    with working_directory(cfg.config_path):
        pages,files = script_pages(cfg.nbs_path)
        docs = scan(cfg.nbs_path, nbproc=OctavoProc(local_lib=local_libraries(cfg))) + pages
        site = Site(docs, root=cfg.nbs_path, files=files, **settings)
        if (miss := site.build()): print(miss)
        if (post := cfg.get('docs_post_build')):
            out = Path(site.settings['output']).expanduser()
            if not out.is_absolute(): out = cfg.nbs_path/out
            import_obj(post)(out.resolve(), cfg)

# %% ../nbs/api/21_octavo.ipynb #0d38402b
def octavo_readme(
    path:str=None, # Path to the project or its notebooks
    chk_time:bool=False, # Only build if the source is newer
    contributing:bool=False, # Render CONTRIBUTING instead of README
):
    "Render a repository Markdown document from a notebook's stored outputs"
    cfg = get_config(path)
    nbname = cfg.get('contributing_nb', 'contributing.ipynb') if contributing else cfg.readme_nb
    root = Path(path).absolute() if path else cfg.nbs_path
    src = root/nbname
    if not src.exists(): src = cfg.nbs_path/nbname
    if not src.exists(): return
    name = 'CONTRIBUTING' if contributing else 'README'
    dest = cfg.config_path/f'{name}.md'
    if chk_time and _doc_mtime_not_older(dest, src): return
    octavo_config(cfg.nbs_path)
    with working_directory(cfg.config_path):
        proc = OctavoProc(strip_libs=local_libraries(cfg))
        doc = md2doc(ipynb2md(src, nbproc=proc))
        head = f'# {doc.meta["title"]}\n\n' if doc.meta.get('title') else ''
        if desc:=doc.meta.get('description'): head += f'{desc}\n\n'
        md2gfm(head + doc.body, dest=dest, imgdir=cfg.config_path/f'{name}_files', raw=('md', 'html'))
