"""A notebook processor

Docs: https://nbdev.fast.ai/api/process.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/03_process.ipynb.

# %% auto #0
__all__ = ['opt_set', 'instantiate', 'NBProcessor', 'Processor']

# %% ../nbs/api/03_process.ipynb #59172c3d
from .config import *
from .maker import *
from .imports import *

from fastcore.nbio import *
from fastcore.nbio import _meta_directives
from fastcore.script import *
from fastcore.imports import *

from collections import defaultdict

# %% ../nbs/api/03_process.ipynb #e6701805
def opt_set(var, newval):
    "newval if newval else var"
    return newval if newval else var

# %% ../nbs/api/03_process.ipynb #98c9d556
def instantiate(x, **kwargs):
    "Instantiate `x` if it's a type"
    return x(**kwargs) if isinstance(x,type) else x

def _mk_procs(procs, nb): return L(procs).map(instantiate, nb=nb)

# %% ../nbs/api/03_process.ipynb #ab147efe
def _is_direc(f): return getattr(f, '__name__', '-')[-1]=='_'

# %% ../nbs/api/03_process.ipynb #7c81f109
class NBProcessor:
    "Process cells and nbdev comments in a notebook"
    def __init__(self, path=None, procs=None, nb=None, debug=False, rm_directives=True, process=False):
        self.nb = read_nb(path) if nb is None else nb
        self.lang = nb_lang(self.nb)
        for cell in self.nb.cells: cell.directives_ = cell.directives
        nbdirs = {k:v for k,v in _meta_directives(self.nb).items() if not any(k in c.directives_ for c in self.nb.cells)}
        if nbdirs:
            fc = first(c for c in self.nb.cells if c.cell_type=='code')
            if fc is not None: fc.directives_ = nbdirs | fc.directives_
        if rm_directives:
            for cell in self.nb.cells: cell.remove_directives(quarto=rm_directives=='quarto')
        self.procs = _mk_procs(procs, nb=self.nb)
        self.debug,self.rm_directives = debug,rm_directives
        if process: self.process()

    def _process_cell(self, proc, cell):
        if not hasattr(cell,'source'): return
        if cell.cell_type=='code' and cell.directives_:
            # Option 1: `proc` is directive name with `_` suffix
            f = getattr(proc, '__name__', '-').rstrip('_')
            if f in cell.directives_: self._process_comment(proc, cell, f)
            
            # Option 2: `proc` contains a method named `_{directive}_`
            for cmd in cell.directives_:
                f = getattr(proc, f'_{cmd}_', None)
                if f: self._process_comment(f, cell, cmd)
        if callable(proc) and not _is_direc(proc): cell = opt_set(cell, proc(cell))

    def _process_comment(self, proc, cell, cmd):
        args = cell.directives_[cmd].split()
        if self.debug: print(cmd, args, proc)
        return proc(cell, *args)
        
    def _proc(self, proc):
        if hasattr(proc,'begin'): proc.begin()
        for cell in self.nb.cells: self._process_cell(proc, cell)
        if hasattr(proc,'end'): proc.end()
        self.nb.cells = [c for c in self.nb.cells if c and getattr(c,'source',None) is not None]
        for i,cell in enumerate(self.nb.cells): cell.idx_ = i

    def process(self):
        "Process all cells with all processors"
        for proc in self.procs: self._proc(proc)

# %% ../nbs/api/03_process.ipynb #fa1f8668
class Processor:
    "Base class for processors"
    def __init__(self, nb): self.nb = nb
    def cell(self, cell): pass
    def __call__(self, cell): return self.cell(cell)
