"""Author nbdev notebooks as source, documentation, examples, and tests. Ensure this guidance is in context before any notebook edit.

# Source

Write notebooks to be read top-to-bottom, interleaving implementation, explanation, examples, outputs, and failure demonstrations. These conventions target published libraries; match surrounding notebooks in internal projects.

Check the file, not the repo: `# AUTOGENERATED! DO NOT EDIT!` names the source notebook; `# %% ../nbs/04_usage.ipynb #a45f753a` identifies the source cell. Edit that notebook, never generated modules, `__all__`, `_modidx.py`, or module docstrings; `nbdev-export` regenerates them. Unmarked modules are hand-written. Use notebooks where narrative/examples teach the API, plain `.py` for dense mechanism iterated under pytest. Tests follow source form: lesson cells for notebooks, `tests/*.py` for plain modules.

For project-level questions, read `nbs/index.ipynb`, the source of README.md; regenerate with `nbdev-readme` after changes.

# Structure and authoring

Choose tutorial, how-to, explanation, or reference. Open with an H1 title cell and `>` subtitle, then a brief introduction. Use H2s for major concepts without fragmenting short narratives. Each heading belongs in its own markdown cell so Jupyter can collapse sections.

Before changing a notebook, read the whole notebook or a summary of every cell. For a new notebook, read a role model such as claudette's `00_core.ipynb` to learn the literate form.

Develop one idea at a time: small implementation, explanation, executable lesson, assertions where useful. Introduce each lesson in markdown; split it when the introduction becomes complicated. Extend existing examples rather than adding near-duplicates. Build classes with `@patch` beside each method's explanation unless that obscures the API.

For new behavior, choose its narrative position, write the lesson first, run preceding cells as needed, and see it fail. Add its markdown introduction and implementation above it, then run implementation and lesson to see it pass. For bugs, revise an existing example to exercise the failing path; if no revision fits, add an assertion to it. If no documented behavior changes, change no lesson cells. Never add a cell merely to witness a fix.

Read existing examples before experimenting. Explore in the notebook, not in a separate kernel check; retain useful explorations as lessons and delete those that teach nothing worth keeping.

Reserve underscore names for machinery without a coherent independent contract. Internal use can justify exposing an abstraction; helpers useful only internally may indicate awkward design.

# Prose and module documentation

Markdown explains rationale, distinctions, and guarantees, not code line-by-line or empty transitions. Place it where it reads correctly on the generated page, normally after the definition. Use short symbol docstrings, parameter/return docments beside signatures, and backticked symbol names for nbdev links. Extended explanation, examples, and warnings belong in markdown.

The module docstring combines the title's `>` description with exported markdown after H1. Use one exported markdown cell per major section for long docstrings. Since `doc(module)` also lists functions, module prose should teach shared constraints and workflows, not repeat individual API documentation.

`#| exportd` includes a code cell as fenced source in the module docstring, not module code. Use compact runnable demos after their required definitions; end the preceding exported summary with a colon. Only exported cells join the docstring, so definitions between that summary and demo do not separate them there.

Check claims by running code before documenting them; preview assembly with `nbdev.export.nb_mdoc`. A docstring beyond the default summary causes `nbdev-export` to include the module in package documentation and `llms.txt`; write these summaries for modules meant to be read independently. Export the opening paragraphs of `index.ipynb` for the package intro.

# Lesson cells

Write page content, not standalone test cells (except rare hidden checks): realistic values, minimal setup, reused objects, and direct assertions that support the lesson. End lesson cells with an informative displayed value when there is something useful to show. Compact `_repr_markdown_` or structured summaries can make later examples readable; plots, tables, images, and HTML also provide evidence. Explain what matters in large outputs and keep stored results focused.

Use `fastcore.test` assertions and `expect_fail` in ordinary code cells, with one focused error example per contract. Keep check plumbing, mocks, dense comprehensions, and long setup out of reader-facing examples: extract a small helper or hide the check.

Review these as rewrite signals, not absolute rules:

- Comments often mark a split into prose and code; numbered steps suggest separate markdown/code pairs. Keep comments that state constraints code cannot show.
- A sentence-wrapped `print` belongs in prose plus a displayed value; final `print(x)` loses rich repr compared with bare `x`.
- Reassignments through stages can hide useful intermediate displays; blank-line groups suggest cell boundaries with their own introductions.
- Near-duplicate examples should make the differing argument the narrative, rather than repeat setup.
- Error-demonstration `try`/`except` usually wants `expect_fail`; long docstrings want markdown.
- Resolve TODO/FIXME example comments or move them to issues.

# State and execution

Define values near first use, introduce shared setup, reuse established objects, and don't reassign names later cells depend on. End exploratory cells with the expression recording what was learned when useful.

Keep imports in dedicated cells, including in lessons: docs builds execute import-containing cells in fresh namespaces, so mixing imports with state-dependent code can fail or run code at documentation time.

Stored outputs are generated artifacts and may be stale during editing. Do not stop, clear them manually, or manipulate notebook JSON because output no longer matches source. At PR time, regenerate with `nbdev-test --save` when the project needs saved outputs updated.

# Directives and nbdev v3

- `#| default_exp` names the generated module; `#| export` includes a cell there. Exported underscore helpers need not join the public API.
- `#| hide` hides distracting necessities from the page.
- `#| eval: false` is for code that must not run, not broken code; it cannot supply state to evaluated cells.
- Directives may instead be metadata: `{"nbdev": {"export": "true"}}`. The toolchain honors both; `mk_cell(...).directives` merges them with content winning conflicts.

nbdev v3 (Jan 2026) uses `pyproject.toml`, not `settings.ini`: metadata in `[project]`, nbdev settings in `[tool.nbdev]` (default `nbs_path='nbs'`, `doc_path='_docs'`), version in `__init__.py` via `dynamic = ["version"]`, and `_modidx` in `[project.entry-points.nbdev]`. CLIs use hyphens (`nbdev-export`, `nbdev-test`); Python names retain underscores. GitHub actions are `fastai/workflows/nbdev3-ci` and `quarto-ghp3`.

# Finish

Revise affected prose, displays, and assertions together; changed assertions must fail on old code and pass on new. Re-read the touched narrative for readability: tests cannot catch documentation damage. Run `nbdev-test <nb>`.
"""
