"""Run unit tests on notebooks in parallel

Docs: https://nbdev.fast.ai/api/test.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/12_test.ipynb.

# %% auto #0
__all__ = ['test_nb', 'nbdev_test']

# %% ../nbs/api/12_test.ipynb #45e10c3f
import time,os,sys,io,traceback,contextlib,inspect,signal,asyncio,threading
from fastcore.basics import *
from fastcore.imports import *
from fastcore.foundation import *
from fastcore.parallel import *
from fastcore.script import *
from fastcore.meta import delegates

from .config import *
from .doclinks import *
from .process import NBProcessor, nb_lang
from .frontmatter import nb_frontmatter

from fastcore.nbio import *
from execnb.shell import *

# %% ../nbs/api/12_test.ipynb #dc8994ac
_cur_nb = [None]
_cur_shell = [None]

def _await_chain(t):
    "One frame per coroutine in task `t`'s await chain, deepest last: where a suspended hang actually sits"
    co = t.get_coro()
    while co is not None:
        f = getattr(co, 'cr_frame', None) or getattr(co, 'ag_frame', None) or getattr(co, 'gi_frame', None)
        if f is not None: yield f, f.f_lineno
        co = getattr(co, 'cr_await', None) or getattr(co, 'ag_await', None) or getattr(co, 'gi_yieldfrom', None)

def _int_handler(signum, frame):
    "Dump the running notebook's stack and exit; installed on SIGINT by `test_nb`"
    if _cur_nb[0] is not None:
        buf = io.StringIO()
        traceback.print_stack(frame, file=buf)
        k = _cur_shell[0]
        if k is not None:
            f = sys._current_frames().get(k._thread.ident)
            if f is not None:
                print('\n--- shell loop thread ---', file=buf)
                traceback.print_stack(f, file=buf)
            with contextlib.suppress(RuntimeError):
                for t in asyncio.all_tasks(k.loop):
                    print(f'\n{t}', file=buf)
                    buf.writelines(traceback.StackSummary.extract(_await_chain(t)).format())
        os.write(2, f'\n=== nbdev-test interrupted: {_cur_nb[0]} ===\n{buf.getvalue()}'.encode())
    os._exit(130)

# %% ../nbs/api/12_test.ipynb #3f4fa1ad
def test_nb(
    fn,  # file name of notebook to test
    skip_flags=None,  # list of flags marking cells to skip
    force_flags=None,  # list of flags marking cells to always run
    do_print=False,  # print completion?
    showerr=True,  # print errors to stderr?
    basepath=None,  # path to add to sys.path
    verbose=False,  # stream stdout/stderr from cells to console?
    save=False,  # write outputs back to notebook on success?
    profile:bool=None, # load the IPython profile, as `ipykernel` does? (default: `exec_profile` config key)
    cell_timeout:int=600, # seconds before each cell times out (None: no limit)
    cell_timing_min:float=None # print cells slower than this many seconds (None: no timing output)
):
    "Execute tests in notebook in `fn` except those with `skip_flags`"
    if not IN_NOTEBOOK and threading.current_thread() is threading.main_thread(): signal.signal(signal.SIGINT, _int_handler)
    fn = Path(fn)
    _cur_nb[0] = fn
    if basepath: sys.path.insert(0, str(basepath))
    prev_test = os.environ.get('IN_TEST')
    if not IN_NOTEBOOK: os.environ['IN_TEST'] = '1'
    try:
        flags=set(L(skip_flags)) - set(L(force_flags))
        nb = NBProcessor(fn, rm_directives=False, process=True).nb
        fm = nb_frontmatter(nb)
        if str2bool(fm.get('skip_exec', False)) or nb_lang(nb) != 'python': return True, 0

        dflt = fm_default_eval(fm)
        def _no_eval(cell):
            if cell.cell_type != 'code': return True
            if not does_cell_eval(cell, dflt): return True
            return flags & (getattr(cell, 'directives_', {}) or {}).keys()

        def _postproc(cell):
            elapsed = cell.metadata['execution']['total']
            if cell_timing_min is not None and elapsed > cell_timing_min: print(f'{fn.name}:{cell.id}: {elapsed:.3f}s')

        start = time.time()
        if profile is None: profile = bool(get_config(fn.parent).exec_profile)
        k = CaptureShell(fn, profile=profile)
        _cur_shell[0] = k
        if do_print: print(f'Starting {fn}')
        try:
            with working_directory(fn.parent):
                k.run_all(nb, exc_stop=True, preproc=_no_eval, postproc=_postproc, verbose=verbose, cell_timeout=cell_timeout)
                if save: write_nb(nb, fn)
                res = True
        except: 
            if showerr: sys.stderr.write(k.prettytb(fname=fn)+'\n')
            res=False
        if k.leaks and showerr: sys.stderr.write(f'{fn}: {len(k.leaks)} leaked task(s) survived cancellation\n')
        if do_print: print(f'- Completed {fn}')
        return res,time.time()-start
    finally:
        _cur_nb[0] = _cur_shell[0] = None
        if prev_test is None: os.environ.pop('IN_TEST', None)
        else: os.environ['IN_TEST'] = prev_test


# %% ../nbs/api/12_test.ipynb #d8bf1f1b-935d-4b69-ba96-827c5d7213f0
def _keep_file(
    p:Path, # filename for which to check for `indicator_fname`
    ignore_fname:str # filename that will result in siblings being ignored
) -> bool:
    "Returns False if `indicator_fname` is a sibling to `fname` else True"
    if p.exists(): return not bool(p.parent.ls().attrgot('name').filter(lambda x: x == ignore_fname))
    else: True

# %% ../nbs/api/12_test.ipynb #f8cc6a61-a48e-4ab1-89a9-18316ca795d6
@call_parse(pos=['path'])
@delegates(nbglob_cli)
def nbdev_test(
    path:str=None,  # A notebook name or glob to test
    flags:str='',  # Space separated list of test flags to run that are normally ignored
    n_workers:int=None,  # Number of workers
    timing:bool=False,  # Time each notebook to see which are slow
    do_print:bool=False, # Print start and end of each notebook
    pause:float=0.01,  # Pause time (in seconds) between notebooks to avoid race conditions
    ignore_fname:str='.notest', # Filename that will result in siblings being ignored
    verbose:bool=False, # Print stdout/stderr from notebook cells?
    save:bool=False, # Write outputs back to notebooks on success?
    cell_timeout:int=600, # Seconds before each cell times out (0: no limit)
    cell_timing_min:float=None, # Print cells slower than this many seconds (None: no timing output)
    **kwargs
):
    "Test in parallel notebooks matching `path`, passing along `flags`"
    cfg = get_config(Path(path).resolve() if path else None)
    skip_flags = cfg.tst_flags
    if isinstance(skip_flags, str): skip_flags = skip_flags.split()
    force_flags = flags.split()
    files = nbglob(path, as_path=True, **kwargs)
    files = [f.absolute() for f in sorted(files) if _keep_file(f, ignore_fname)]
    if len(files)==0: return print('No files were eligible for testing')

    if n_workers is None: n_workers = 0 if len(files)==1 else min(num_cpus(), 8)
    if IN_NOTEBOOK: kw = {'method':'spawn'} if os.name=='nt' or sys.platform=='darwin' else {'method':'forkserver'}
    else: kw = {'method':'spawn'} if sys.platform=='darwin' else {}
    wd_pth = cfg.nbs_path
    with working_directory(wd_pth if (wd_pth and wd_pth.exists()) else os.getcwd()):
        try:
            results = parallel(test_nb, files, skip_flags=skip_flags, force_flags=force_flags, n_workers=n_workers,
                               basepath=cfg.config_path, pause=pause, do_print=do_print, verbose=verbose, save=save,
                               cell_timeout=cell_timeout or None, cell_timing_min=cell_timing_min, **kw)
        except KeyboardInterrupt:
            sys.stderr.write('\nnbdev-test interrupted; in-flight notebook stacks shown above\n')
            sys.exit(130)
    passed,times = zip(*results)
    if all(passed): print("Success.")
    else: 
        _fence = '='*50
        failed = '\n\t'.join(f.name for p,f in zip(passed,files) if not p)
        sys.stderr.write(f"\nnbdev Tests Failed On The Following Notebooks:\n{_fence}\n\t{failed}\n")
        sys.exit(1)
    if timing:
        for i,t in sorted(enumerate(times), key=lambda o:o[1], reverse=True): print(f"{files[i].name}: {int(t)} secs")
