# AUTOGENERATED! DO NOT EDIT! File to edit: ../tests/update_directives.ipynb.

# %% auto 0
__all__ = []

# %% ../tests/update_directives.ipynb 5
#| output: False
"""
Think of something
that makes you smile 
and brightens your day
"""

# System import
import os
# Local import
import nbdev.serve

# %% ../tests/update_directives.ipynb 6
# |eval: false
print("1. test export and eval")

# %% ../tests/update_directives.ipynb 8
#| eval: false
print("3. nr 2 should be missing from the py file")
